export enum DeliveryRegions {
    CHISINAU = "CHISINAU",
    AEROPORT_CHISINAU = "AEROPORT_CHISINAU",
    CHISINAU_MUNICIPII = "CHISINAU_MUNICIPII",
    BALTI = "BALTI",
    BENDER = "BENDER",
    BASARABEASCA = "BASARABEASCA",
    BRICENI = "BRICENI",
    BUCOVAT = "BUCOVAT",
    VULCANESTI = "VULCANESTI",
    GLODENI = "GLODENI",
    DROCHIA = "DROCHIA",
    DUBASARI = "DUBASARI",
    EDINET = "EDINET",
    CAHUL = "CAHUL",
    CALARASI = "CALARASI",
    CANTEMIR = "CANTEMIR",
    CAUSENI = "CAUSENI",
    COMRAT = "COMRAT",
    LEOVA = "LEOVA",
    LIPCANI = "LIPCANI",
    NISPORENI = "NISPORENI",
    ANENII_NOI = "ANENII_NOI",
    OCNITA = "OCNITA",
    ORHEI = "ORHEI",
    REZINA = "REZINA",
    RIBNITA = "RIBNITA",
    RISCANI = "RISCANI",
    SOROCA = "SOROCA",
    STRASENI = "STRASENI",
    TARACLIA = "TARACLIA",
    TVARDITA = "TVARDITA",
    TIRASPOL = "TIRASPOL",
    UNGHENI = "UNGHENI",
    FALESTI = "FALESTI",
    FLORESTI = "FLORESTI",
    HINCESTI = "HINCESTI",
    CEADIR_LUNGA = "CEADIR_LUNGA",
    CIMISLIA = "CIMISLIA",
    SOLDANESTI = "SOLDANESTI",
    STEFAN_VODA = "STEFAN_VODA",
    IALOVENI = "IALOVENI"
}

export const DeliveryRegionsArr = Object.values(DeliveryRegions).filter(value => typeof value === 'string') as string[];

const deliveryPrices: Record<DeliveryRegions, number> = {
    [DeliveryRegions.CHISINAU]: 0,
    [DeliveryRegions.AEROPORT_CHISINAU]: 100,
    [DeliveryRegions.CHISINAU_MUNICIPII]: 80,
    [DeliveryRegions.BALTI]: 1350,
    [DeliveryRegions.BENDER]: 680,
    [DeliveryRegions.BASARABEASCA]: 1170,
    [DeliveryRegions.BRICENI]: 2340,
    [DeliveryRegions.BUCOVAT]: 340,
    [DeliveryRegions.VULCANESTI]: 1790,
    [DeliveryRegions.GLODENI]: 1750,
    [DeliveryRegions.DROCHIA]: 1870,
    [DeliveryRegions.DUBASARI]: 500,
    [DeliveryRegions.EDINET]: 2060,
    [DeliveryRegions.CAHUL]: 1770,
    [DeliveryRegions.CALARASI]: 470,
    [DeliveryRegions.CANTEMIR]: 1240,
    [DeliveryRegions.CAUSENI]: 700,
    [DeliveryRegions.COMRAT]: 970,
    [DeliveryRegions.LEOVA]: 1220,
    [DeliveryRegions.LIPCANI]: 2570,
    [DeliveryRegions.NISPORENI]: 770,
    [DeliveryRegions.ANENII_NOI]: 300,
    [DeliveryRegions.OCNITA]: 2330,
    [DeliveryRegions.ORHEI]: 435,
    [DeliveryRegions.REZINA]: 1130,
    [DeliveryRegions.RIBNITA]: 1200,
    [DeliveryRegions.RISCANI]: 1760,
    [DeliveryRegions.SOROCA]: 1580,
    [DeliveryRegions.STRASENI]: 240,
    [DeliveryRegions.TARACLIA]: 1520,
    [DeliveryRegions.TVARDITA]: 1140,
    [DeliveryRegions.TIRASPOL]: 750,
    [DeliveryRegions.UNGHENI]: 1100,
    [DeliveryRegions.FALESTI]: 1340,
    [DeliveryRegions.FLORESTI]: 1290,
    [DeliveryRegions.HINCESTI]: 370,
    [DeliveryRegions.CEADIR_LUNGA]: 1290,
    [DeliveryRegions.CIMISLIA]: 600,
    [DeliveryRegions.SOLDANESTI]: 1210,
    [DeliveryRegions.STEFAN_VODA]: 950,
    [DeliveryRegions.IALOVENI]: 150
};

export function getDeliveryPrice(region: DeliveryRegions, price: number): number {
    return deliveryPrices[region] === 0 ? price > 500 ? 0 : 80 : deliveryPrices[region];
}