export enum DeliveryRegions {
  CHISINAU = 'CHISINAU',
  BALTI = 'BALTI',
  ANENII_NOI = 'ANENII_NOI',
  BASARABEASCA = 'BASARABEASCA',
  BENDER = 'BENDER',
  BRICENI = 'BRICENI',
  CAHUL = 'CAHUL',
  CALARASI = 'CALARASI',
  CANTEMIR = 'CANTEMIR',
  CAUSENI = 'CAUSENI',
  CEADIR_LUNGA = 'CEADIR_LUNGA',
  CIMISLIA = 'CIMISLIA',
  COMRAT = 'COMRAT',
  DROCHIA = 'DROCHIA',
  DUBASARI = 'DUBASARI',
  EDINET = 'EDINET',
  FALESTI = 'FALESTI',
  FLORESTI = 'FLORESTI',
  GLODENI = 'GLODENI',
  HINCESTI = 'HINCESTI',
  IALOVENI = 'IALOVENI',
  LEOVA = 'LEOVA',
  NISPORENI = 'NISPORENI',
  OCNITA = 'OCNITA',
  ORHEI = 'ORHEI',
  REZINA = 'REZINA',
  RIBNITA = 'RIBNITA',
  RISCANI = 'RISCANI',
  SOLDANESTI = 'SOLDANESTI',
  SOROCA = 'SOROCA',
  STEFAN_VODA = 'STEFAN_VODA',
  STRASENI = 'STRASENI',
  TARACLIA = 'TARACLIA',
  TIRASPOL = 'TIRASPOL',
  UNGHENI = 'UNGHENI',
}

export const DeliveryRegionsArr = Object.values(DeliveryRegions).filter(
  value => typeof value === 'string'
) as string[];

const deliveryPrices: Record<DeliveryRegions, number> = {
  [DeliveryRegions.CHISINAU]: 80,
  [DeliveryRegions.BALTI]: 1350,
  [DeliveryRegions.ANENII_NOI]: 300,
  [DeliveryRegions.BASARABEASCA]: 1170,
  [DeliveryRegions.BENDER]: 680,
  [DeliveryRegions.BRICENI]: 2340,
  [DeliveryRegions.CAHUL]: 1770,
  [DeliveryRegions.CALARASI]: 470,
  [DeliveryRegions.CANTEMIR]: 1240,
  [DeliveryRegions.CAUSENI]: 700,
  [DeliveryRegions.CEADIR_LUNGA]: 1290,
  [DeliveryRegions.CIMISLIA]: 600,
  [DeliveryRegions.COMRAT]: 970,
  [DeliveryRegions.DROCHIA]: 1870,
  [DeliveryRegions.DUBASARI]: 500,
  [DeliveryRegions.EDINET]: 2060,
  [DeliveryRegions.FALESTI]: 1340,
  [DeliveryRegions.FLORESTI]: 1290,
  [DeliveryRegions.GLODENI]: 1750,
  [DeliveryRegions.HINCESTI]: 370,
  [DeliveryRegions.IALOVENI]: 150,
  [DeliveryRegions.LEOVA]: 1220,
  [DeliveryRegions.NISPORENI]: 770,
  [DeliveryRegions.OCNITA]: 2330,
  [DeliveryRegions.ORHEI]: 435,
  [DeliveryRegions.REZINA]: 1130,
  [DeliveryRegions.RIBNITA]: 1200,
  [DeliveryRegions.RISCANI]: 1760,
  [DeliveryRegions.SOLDANESTI]: 1210,
  [DeliveryRegions.SOROCA]: 1580,
  [DeliveryRegions.STEFAN_VODA]: 950,
  [DeliveryRegions.STRASENI]: 240,
  [DeliveryRegions.TARACLIA]: 1520,
  [DeliveryRegions.TIRASPOL]: 750,
  [DeliveryRegions.UNGHENI]: 1100,
};

export function getDeliveryPrice(region: DeliveryRegions): number {
  return deliveryPrices[region];
}
