export enum ProductContent {
    ACCESSORIES_FOR_DRINKS = "ACCESSORIES_FOR_DRINKS",
    ACCESSORIES_FOR_TEA_COFFEE = "ACCESSORIES_FOR_TEA_COFFEE",
    FOR_OFFICE = "FOR_OFFICE",
    FOR_HOME = "FOR_HOME",
    GAMES = "GAMES",
    TOYS = "TOYS",
    STATIONERY_ITEMS = "STATIONERY_ITEMS",
    COFFEE_TEA = "COFFEE_TEA",
    MUG_THERMOS_BOTTLE_FOR_WATER = "MUG_THERMOS_BOTTLE_FOR_WATER",
    HONEY_JAM_CARAMEL_PEANUT_BUTTER = "HONEY_JAM_CARAMEL_PEANUT_BUTTER",
    NUTS_DRY_FRUITS_SPICES = "NUTS_DRY_FRUITS_SPICES",
    CHOCOLATE_BISCUITS_CANDY = "CHOCOLATE_BISCUITS_CANDY",
    FIRECRACKER = "FIRECRACKER",
    PACKAGING_CRAFT_BOX = "PACKAGING_CRAFT_BOX",
    PACKAGING_CARDBOARD_BOX_DESIGN = "PACKAGING_CARDBOARD_BOX_DESIGN",
    PACKAGING_WOODEN = "PACKAGING_WOODEN",
    PACKAGING_CUSTOM_BAG = "PACKAGING_CUSTOM_BAG",
    PACKAGING_CUSTOM_DESIGN = "PACKAGING_CUSTOM_DESIGN",
  };
  
  export const ProductContentArr = Object.values(ProductContent).filter(value => typeof value === 'string') as string[];